### PR TITLE
Create SSB Survey and Data Efforts Tracking

### PR DESCRIPTION
**Pull request by SWerner2**
Let me know if this is okay, but I see the google sheet as being the easiest to maintain. If there is a better way, please let me know!

### CODE REVIEW

**Comment by mle2718** [comment]
@SWerner2  can you rename the file to end in .md? This will let github display the file properly on the web.

**Comment by mle2718** [comment]
no i meant this file:

https://github.com/SWerner2/READ-SSB-Lee-metadata/blob/master/SSB%20Survey%20and%20Data%20Efforts%20Tracking

should be renamed to 
https://github.com/SWerner2/READ-SSB-Lee-metadata/blob/master/SSB%20Survey%20and%20Data%20Efforts%20Tracking.md

**Comment by SWerner2** [comment]
Sorry, that is what I was trying to change (learning curve). We will get there, let me know if I fixed it.

**Comment by mle2718** [comment]
Looks good.

**Comment by mle2718** [comment]
@SWerner2 : You can delete your fork, it's currently identical to the main branch of this repository.
I'll momentarily be making a change to the readme.md doc in this repository, so if you want to continue editing in your fork, you can also merge changes from this repository into your fork.

**Pull request merged**
